name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.11.2
    with:
      number-of-agents: 3
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="build" --agent-count=3
      parallel-commands: |
        yarn nx-cloud record -- yarn nx workspace-lint
        yarn nx-cloud record -- yarn nx format:check
        yarn nx-cloud record -- yarn check-lockfile
      parallel-commands-on-agents: |
        yarn nx affected --target=lint --exclude=workspace --parallel=3
        yarn nx affected --target=test --exclude=workspace --parallel=3 --ci --code-coverage
        yarn nx affected --target=build,check-dependencies --exclude=workspace --parallel=3

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.11.2
    with:
      number-of-agents: 3
